AWSTemplateFormatVersion: 2010-09-09
Description: ''
###
### Export the ARN of the Certificate that can be used when setting up Custom Domain Names in API Gateway.
###

# need pass CDNDomainName as parameter as it was deployed in eu-west-1 and this stack is deployed in us-east-1

Parameters:
  ProductName:
    Type: String
    Description: Name of the product

  TopLevelDomainName:
    Type: String
    Description: Top level domain name for the hosted zone
  
  SubDomainName:
    Type: String
    Description: Sub domain name for the hosted zone

  Environment:
    Type: AWS::SSM::Parameter::Value<String>
    Default: Environment
    Description: Environment parameter from SSM

Conditions:
  IsProduction: !Equals 
    - !Ref Environment
    - production

# Certificate
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !If 
        - IsProduction
        - !Sub ${SubDomainName}.${TopLevelDomainName}
        - !Sub ${Environment}-${SubDomainName}.${TopLevelDomainName}
      ValidationMethod: DNS
      SubjectAlternativeNames:
        - !If 
          - IsProduction
          - !Sub www.${SubDomainName}.${TopLevelDomainName}
          - !Sub www.${Environment}-${SubDomainName}.${TopLevelDomainName}
        - !If 
          - IsProduction
          - ${TopLevelDomainName}

Outputs:
  CertificateOutput:
    Description: CertificateExport
    Export:
      Name: !Sub ${ProductName}-certificate
    Value:
      !Ref Certificate
