# used by: CodeBuild in Deploy phase

version: 0.2

env:
  variables:
    WHATEVER: "whatever"

phases:
  install:
    runtime-versions:
      nodejs: 20
      python: 3.10

    commands:
      - ls -las
      - echo Changing shell scripts to 755...
      - find . -name '*.sh' -exec chmod 755 {} ';'
      - find backend/cicd -name '*.js' -exec chmod 755 {} ';'
      - find backend/cicd -name '*.py' -exec chmod 755 {} ';'
      - chmod 755 backend/cicd/scripts/*
      - echo Adding backend/cicd/scripts to PATH...
      - export PATH=$(pwd)/backend/cicd/scripts:$PATH
    

  build:
    commands:
      - echo Changing role...
      - . ./backend/cicd/scripts/changerole.sh
      - aws sts get-caller-identity
      - echo Deploying...
      - cd backend/product
      - ls -las
      # - ./deploy.sh


  post_build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}
      - echo All zip files
      - find . -name '*.zip' -o -name '*.ZIP'

artifacts:
  files:
    - '**/*'
  discard-paths: no
