# used by: CodeBuild in Deploy phase

version: 0.2

env:
  variables:
    WHATEVER: "whatever"

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8

    commands:
      - echo Modifying all shell scripts to mode 755...
      - find . -name "*.sh" -exec chmod 755 '{}' ';'
      - echo Modifying all cicd nodejs scripts to mode 755...
      - find cicd -name "*.js" -exec chmod 755 '{}' ';'
      - find cicd -name '*.py' -exec chmod 755 {} ';'
      - echo Adding cicd/scripts to PATH...
      - export PATH=$(pwd)/cicd/scripts:$PATH
      - echo "Installing all the tools the Codebuilds may ever need..."
      - pip3 install --upgrade pip
      - aws codeartifact login --tool pip --repository hctools --domain hc --domain-owner 256928933720 --region eu-west-1
      - pip3 install --root-user-action=ignore --upgrade hctools
      - pip3 install --root-user-action=ignore --upgrade python-stripzip

  build:
    commands:
      - echo Changing role...
      - . ./cicd/scripts/changerole.sh
      - echo Deploying...
      - cd product
      - ./deploy.sh

artifacts:
  files:
    - cicd/**/*
  discard-paths: no
