AWSTemplateFormatVersion: 2010-09-09
Description: Environment infrastructure for the web site

Parameters:
  ProductName:
    Type: String
    Default: Website

Conditions:
  AllwaysFalse: !Equals
    - true
    - false

Resources:
  NeverDeployed:
    Condition: AllwaysFalse
    Type: AWS::SNS::Topic

Outputs:
  ProductNameOutput:
    Description: Website name
    Export:
      Name: WebsiteName
    Value: !Ref ProductName